<?php
	$clientid = Mage::getSingleton('customer/session')->getCustomer()->getId(); // get customer id
	$chatdata = Mage::getModel('chatbot/chatdata')->load($clientid, 'customer_id'); // load profile info from customer id

	// TODO please
	$tg_apikey = Mage::getStoreConfig('chatbot_enable/telegram_config/telegram_api_key');
	$getme = "https://api.telegram.org/bot" . $tg_apikey . "/getMe";
	$response = json_decode(file_get_contents($getme), true);
	$tg_username = null;
	if ($response["ok"])
		$tg_username = $response["result"]["username"];

	$fb_apikey = Mage::getStoreConfig('chatbot_enable/facebook_config/facebook_api_key');
	$getme = "https://graph.facebook.com/v2.8/me?access_token=" . $fb_apikey;
	$response = json_decode(file_get_contents($getme), true);
	$fb_username = null;
	if (!empty($response))
		$fb_username = $response["id"];
?>
<div class="dashboard">
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
	<div class="page-title">
		<h1><?php echo $this->__('Chatbot Settings') ?></h1>
	</div>
	<form action="<?php echo $this->getUrl('chatbot/settings/save') ?>" method="post" id="form-validate" autocomplete="off">
		<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
		<div class="fieldset">
			<ul class="form-list">
				<li>
					<div class="input-box">
						<input <?php if ($chatdata->getEnableTelegram() == "1") echo "checked"; ?> type="checkbox" title="<?php echo $this->__('Enable Telegram?') ?>" class="checkbox" name="enable_telegram" id="enable_telegram" />
						<label for="enable_telegram" class="required"><em>*</em><?php echo $this->__('Enable Telegram?') ?></label>
					</div>
					<?php if ($tg_username): ?><!-- bot username -->
						<p>
							<?php
								echo $this->__("Start a bot conversation on Telegram") . ": ";
								$url = $chatdata->_tgUrl . $tg_username;
								if (empty($chatdata->getTelegramChatId()))
									$url .= "?start=" . $chatdata->getHashKey();
							?>
							<a href="<?php echo $url; ?>" target="_blank"><?php echo $this->__('Here') ?></a>
						</p>
					<?php endif; ?>
				</li>
				<li>
					<div class="input-box">
						<input <?php if ($chatdata->getEnableFacebook() == "1") echo "checked"; ?> type="checkbox" title="<?php echo $this->__('Enable Facebook?') ?>" class="checkbox" name="enable_facebook" id="enable_facebook" />
						<label for="enable_facebook" class="required"><em>*</em><?php echo $this->__('Enable Facebook?') ?></label>
					</div>
					<?php if ($fb_username): ?><!-- bot username -->
					<p>
						<?php
							echo $this->__("Start a bot conversation on Facebook Messenger") . ": ";
							$url = $chatdata->_fbUrl . $fb_username;
						?>
						<a href="<?php echo $url; ?>" target="_blank"><?php echo $this->__('Here') ?></a>
					</p>
					<?php endif; ?>
				</li>
				<?php
				/*
				<li>
					<div class="input-box">
						<input <?php if ($chatdata->getEnableWhatsapp() == "1") echo "checked"; ?> type="checkbox" title="<?php echo $this->__('Enable Whatsapp?') ?>" class="checkbox" name="enable_whatsapp" id="enable_whatsapp" />
					</div>
					<label for="enable_whatsapp" class="required"><em>*</em><?php echo $this->__('Enable Whatsapp?') ?></label>
				</li>
				<li>
					<div class="input-box">
						<input <?php if ($chatdata->getEnableWechat() == "1") echo "checked"; ?> type="checkbox" title="<?php echo $this->__('Enable Wechat?') ?>" class="checkbox" name="enable_wechat" id="enable_wechat" />
					</div>
					<label for="enable_wechat" class="required"><em>*</em><?php echo $this->__('Enable Wechat?') ?></label>
				</li>
				*/
				?>
			</ul>
		</div>
		<!-- buttons -->
		<p class="required"><?php echo $this->__('* Required Fields') ?></p>
		<div class="buttons-set">
			<p class="back-link">
				<a href="<?php echo $this->getBackUrl() ?>">
					<small>&laquo; </small><?php echo $this->__('Back') ?>
				</a>
			</p>
			<button type="submit" title="<?php echo $this->__('Save') ?>" class="button">
				<span>
					<span>
						<?php echo $this->__('Save') ?>
					</span>
				</span>
			</button>
		</div>
	</form>
</div>