<?php
    $define = $this->getDefine();
    $enabled = $this->getConfigValue('werules_chatbot_messenger/general/enable');
    if ($enabled == $define::ENABLED)
    {
        $challenge_hub = $this->getConfigValue('werules_chatbot_messenger/general/enable_hub_challenge');
        if ($challenge_hub == $define::ENABLED)
        {
            $hub_token = $this->getConfigValue('werules_chatbot_general/general/custom_key');
            $verification_hub = $this->getVerificationHub($hub_token);
            if ($verification_hub)
                echo $verification_hub;
            else
                echo __("Please check your Hub Verify Token.");
        }
        else
            echo $this->requestHandler();
    }
    else
        echo $this->getJsonErrorResponse();
?>